Feature/redocusaurus and furo
sushiswap/sushi-docs pull request #18
Opened 2022-06-21 08:29 UTC by OlaStenberg

Added Furo API docs and API dropdown to navbar

![image](https://user-images.githubusercontent.com/29061789/174753793-a2ccb64f-3024-405c-8380-bdd16b93680a.png)

See:
https://sushi-docs-rfv1c3av5-teamsushi.vercel.app/api/furo

2022-06-21 19:53 UTC, 0xGenghisGoose requested changes
Looks good, if you can make that version change Jiro mentioned & resolve the yarn.lock conflicts real quick this one will get good to go!

2022-06-21 20:10 UTC, OlaStenberg commented on openapi/furo/v1/openapi.yaml
> +  version: "1"
Sure, agree!

2022-06-21 20:10 UTC, OlaStenberg commented
> The side menu seems kinda finicky too, it's not moving down the page accordingly
> 
> If it's limitation with plugin or how it's setup though no biggy. Rest of it LGTM

Yeah, not sure, will have a quick look tomorrow morning

2022-06-22 06:08 UTC, OlaStenberg commented
Yeah, seem to be a known issue a limitation in the plugin, lets roll with it for now? opened an issue at https://github.com/rohit-gohri/redocusaurus/issues/214

2022-06-22 15:32 UTC, jiro-ono commented
Ahh I see, yeah all good let's run with it for now figure it out later

2022-06-22 15:33 UTC, merged